### ISSUE TITLE
module 'vimp' not found

### ISSUE THREAD

**Issue by akiyosi** [svermeulen/vimpeccable#10]
Hi
I installed vimpeccable using `wbthomason/packer.nvim`, but I get the following error. 
<img width="842" alt="スクリーンショット 2020-10-28 23 46 20" src="https://user-images.githubusercontent.com/8478977/97452239-dd53ee80-1977-11eb-95d8-219437289dda.png">

Other lua plugins that I have installed as well seem to be loaded. 
What should I check?

my `setting.lua` like the following :

``` lua
vim.cmd [[packadd packer.nvim]]
-- Only if your version of Neovim doesn't have https://github.com/neovim/neovim/pull/12632 merged
-- vim._update_package_paths()

require('packer').startup(function()
  -- Packer can manage itself as an optional plugin
  use {'wbthomason/packer.nvim', opt = true}

  -- for write vimrc in lua
  use 'svermeulen/vimpeccable'

end)

```

**Comment by svermeulen** [comment]
Are you executing `require('vimp')` before attempting to access it?

**Comment by svermeulen** [comment]
I suppose we should do that automatically.  If someone has added it as a plugin then it's a safe assumption they want it to load

**Comment by akiyosi** [comment]
@svermeulen 
Thanks for quick reply :D 

I have prepared a file `~/.config/nvim/lua/setting.lua`, and in the first stage I load `packer.nvim` using `packadd` and add vimpeccable, and after that process I run `require('vimp')`.

e.g.

``` lua
vim.cmd [[packadd packer.nvim]]
-- Only if your version of Neovim doesn't have https://github.com/neovim/neovim/pull/12632 merged
-- vim._update_package_paths()

require('packer').startup(function()
  -- Packer can manage itself as an optional plugin
  use {'wbthomason/packer.nvim', opt = true}

  -- for write vimrc in lua
  use 'svermeulen/vimpeccable'

end)

require('vimp')
vimp.nnoremap({'silent'}, "<Esc><Esc>", [[:nohlsearch<CR>]])

```

 In this configuration, is the `vimp` loading timing executed later?
I want to write all my settings in a single lua file.

**Comment by svermeulen** [comment]
I tried this, and found that the plugins loaded by packer.nvim don't appear to be loaded at the time when you are attempting to call `vimp.nnoremap`.  A similar problem occurs if you try using vim-plug as I do in the documentation, and then immediately try calling `lua vimp.bind(..)` at the bottom of the init.vim.   This is why in the examples, I had my config represented by another plugin, and made sure that plugin was loaded after vimpeccable.  Having your config inside a plugin also has the advantage that you can build up a library of lua files inside a `lua folder`
