### ISSUE TITLE
Option to make `override` default behavior

### ISSUE THREAD

**Issue by vanhtuan0409** [svermeulen/vimpeccable#15]
Hi, is there anyway that we can make vimpeccable with `override` as default behavior.

Currently I need to pass the override option into every vimpeccable calls

**Comment by svermeulen** [comment]
Sure, we can add that.  I'm curious why you would want this though?  Why do you need to pass override option to all maps?  Wouldn't it be better instead to only add maps that do not conflict with each other?

**Comment by vanhtuan0409** [comment]
@svermeulen I have some annoying problems with Packer.

Every time I run `PackerCompile` or `PackerSync`, there are warnings popup shown from Vimpeccable about duplicate in key mappings. Even tho the old and new mapping is exactly the same. Probably due to Packer reload the configuration causing key bindings re-applied.

Another annoying issue is when I use Vimpeccable on LSP `on_attach` function. When multiple, servers are attached to the same buffer, the mapping is applied multiple time and warnings popup

I have to admit that setting `override` as default behaviour is just a quick hack because I'm too lazy to fix my setup

**Comment by svermeulen** [comment]
Ok I've added this now and described it here:  https://github.com/svermeulen/vimpeccable#advanced-options
