### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by qbedard** [svermeulen/vimpeccable#7]
I don't enjoy being "that guy", but why deviate from the built-in lua API's conventions by using camelCase instead of snake_case?

I found it surprising, and using some of vimpeccable's functions alongside built-in API functions looks disjointed with the differing cases to me.

**Comment by svermeulen** [comment]
Oh, yeah I didn't even realize I was diverging from the standard, but you're right.  Neovim API uses snake case.  In retrospect I should have used that as well.

Maybe what we should do is change to that, and then deprecate the existing methods with warnings

**Comment by svermeulen** [comment]
Ok done.  Thank god for vim-abolish to make this easy to do  :)

**Comment by qbedard** [comment]
> Thank god for vim-abolish to make this easy to do  :)

Omg, amen.

And awesome! Thanks for the quick response and turnaround! Keep up the good work!
